title: Yusong Dong's Homepage
page-top-title: Yusong Dong
top-section-bg-text: Be what you wanna be
home-subtitle: Yusong Dong&ensp;|&ensp;董雨凇
copyright-text: '&copy; Yusong Dong 2026-present. All Rights Reserved.'
